import Head from 'next/head'
import { useQuery } from 'urql'
import { MODEL_QUERY } from '../lib/query'
import Model from '../components/Model';
import {Gallery} from '../styles/Gallery';
import { ReactElement, JSXElementConstructor, ReactFragment, ReactPortal } from 'react';

export default function Home() {
  const [results] = useQuery({query: MODEL_QUERY});
  const {data,fetching,error} = results;

  //check if data is coming in
  if(fetching) return <p>Loading...</p>;

  if(error) return <p> ohh no.... {error.message}</p>
  const models = data.models.data;
  
  return (
    <>
      <Head>
        <title>Styled | Your brand of choice. </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
      </Head>
      <main >
        <p style={{fontSize:'50px', textAlign:'center'}}>STYLED | <span>The Brand of your Choice</span></p>
        <div >
          <Gallery>
          {models.map((item:any)=>{
            return <Model key = {item.attributes.slug} model = {item}/>
          })}
          </Gallery>

          
        </div>

      </main>
    </>
  )
}
